---
version: "3"
services:
 devopsdb:
   image: udaykiran2327/automation:db
   ports:
     - "3306:3306"
  
 application:
   image: udaykiran2327/automation:app
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
